BlueColonySS13/BlueColonySS13

code/game/jobs/job/job.dm
code/modules/client/preference_setup/general/03_background.dm

Adjusts inheritance for economy changes
Adjusts for economy changes

Initial Burger Allowance (Inheritance) Increase

---

code/game/jobs/job/council.dm
code/game/jobs/job/emergency.dm
code/game/jobs/job/hospital.dm
code/game/jobs/job/legal.dm
code/game/jobs/job/police.dm
code/game/jobs/job/science.dm
data/whitelist.txt

Whitelist players by doing the following:
ckey - Job
Example:
ckey is The Flagbearer
job is Mayor
theflagbearer - Mayor

Adds Whitelisting

---

code/modules/government/credit/expenses.dm
code/modules/government/economy/_economy_procs.dm
code/modules/persistence/persistent_economy.dm
code/modules/persistence/persistent_inventory.dm
polaris.dme

Various price and charge adjustments before the planned release of the server.
Stable economies are cool. Sometimes.
:cl:
tweak: Adjusts various items related to the economy.
/:cl:

Economy Pre-Release Minor Fixes & Tweaks

---

config/admins.txt
maps/geminus_neue/geminus_neue.dm
polaris.dme

Remember to tick your files my dudes
It just works

Lot Prices Ticking

---

code/game/machinery/recharger.dm

weapon cells can be charged in wall recharger

---

.gitignore
config/.gitignore
config/config.txt
config/hardwhitelist.txt

Fixes the jobs whitelist system and allows for some config files to be updated as if for production
Functioning functional functionality!
:cl:
fix: Job whitelisting
add: Adds ability to use some config files as if for prod
/:cl:

Job Whitelisting & (Maybe) Lag Fix

---

code/modules/government/president/headoffice/procedures.dm

Puts an html code to the police SOP book sending to the wiki page concerning the police SOPs. My change is very likely to be false in coding, that's why I am asking for someone to proof read it.
New PD players can have a direct reference to the proper, full SOPs. The previous content was just a few lines.
:cl:
/:cl:

Replaces In-Game Police SOP with Active Wiki Police SOP

---

code/game/machinery/vending.dm
code/modules/client/preference_setup/loadout/loadout_general.dm
code/modules/clothing/suits/utility.dm

More Stuff from the To-Do List

---

code/game/area/Space Station 13 areas.dm

Arrivals shuttle no longer vents its holding area. Should fix some lag.
:cl:
/:cl:

Arrivals fix

---

.gitignore
maps/geminus_neue/geminus_neue-1.dmm
maps/geminus_neue/geminus_neue-2.dmm

Fixes the issue with disposals and revamps the maintenance/fire department
The disposals problem was a bit of a problem since it would spit things out into some lots (and contribute to savetimes).
:cl:
fix: Fixes disposals system
tweak: Makes the disposal outlet beneath engineering better
tweak: Separates maintenance department from sanitech area
add: Adds a pretty cool department overall
add: Adds engineering gear
add: Adds firefighting gear
add: Adds water and fuel tanks
add: Adds disposal pipe dispenser
add: Adds MD/PWD/CE office
add: Adds mechanic's garage
fix: Fixes loads more miscellaneous bugs
/:cl:

Map updates

---

code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm

adds eggnog. we had the recipe, just not the result, meaning the recipe made nothing.
it fixes a broken recipe, and allows people to drink eggnog. not that i would encourage that sort of thing, personally.
:cl: thatdanguy23
code: eggnog works now
/:cl:

adds eggnog as a reagent

---

code/game/objects/items/stacks/stack.dm

Title, for some reason the commit diff went weird.
This is the actual only change
```
374		if(!N || (0 > N) || (N > amount))
375			return
376
377+		if(loc != user)	//If we don't have it with us, we probably should not be doing this
378+			to_chat(user, "<span class='warning'>You don't have that anymore!</span>")
379+			return
380
381		var/obj/item/stack/F = src.split(N)
382		if (F)
```
I suppose exploiting and duplicating any material that you can split *such as money* is bad.
:cl:
fix: You can no longer duplicate any sort of material on an invi-tri machine. (and probably any other machine that you insert something)
/:cl:

Fixes invi-tri duplication exploit

---

maps/geminus_neue/geminus_neue_lots.dm

A bunch of miscellaneous edits and tweaks
Better code, better game
:cl:
fix: Fixes Bizlot13 and Officelot2 still showing in the Landlord Management Program, even after being removed from the game
/:cl:

Miscellaneous Fixes & Tweaks

---

code/modules/economy/cash.dm

Title.
Consistancy, and you would probably get confused about how much it actually is.
:cl:
fix: Cash stacks' name get modified on merging.
/:cl:

Merging cash stacks update the name

---

code/modules/persistence/persistent_inventory.dm

Title.
There's probably a reason why `dont_save` marked items shouldn't be saved
:cl:
fix: Items with `dont_save = TRUE` cannot be inserted into the machine even if inside something.
/:cl:

Prevents `dont_save` items from being saved if inside something

---

config/hardwhitelist.txt

changes trying to fix the hardwhitelist
:cl:
/:cl:

changes to hard whitelist

---

config/admins.txt

added quinn/apsychonaut to dev team
:cl:
/:cl:

added quinn/apsychonaut to dev team

---

code/modules/persistence/persistent_banks.dm

Noticed that debts weren't being loaded properly when a character spawned in. Also that PINs were being reset every round. Examined and found that two lines looked reversed. Tested and verified that pin/debt now loads properly
Allows for debt and custom pins
:cl:
fix: Fixed persistent debt and PIN loading
/:cl:

Fix persistant debt and pin

---

code/modules/government/president/landlord.dm

Title.
**[to-do list link redacted due to being publicly editable]**
@ line 67
:cl:
tweak: Mayors can now modify "Minimum Arrears For Tenant Eviction".
/:cl:

Allows mayors (or higher rank) to modify "Minimum Arrears For Tenant Eviction"

---

code/modules/economy/cash.dm

Title.
So many people getting jackpots, got asked to nerf it.
:cl:
balance: All victories on the lottery now have a reduced value.
/:cl:

Nerfs lottery

---

code/game/machinery/computer/betting_terminal.dm
code/game/machinery/computer/slot_machine.dm

Been told it's too easy as well and that it must be harder.
It might be.
:cl:
balance: Increased the risk of gambling.
/:cl:

Nerfs horse races and slot machines

---

code/game/atoms.dm
code/game/objects/items/weapons/implants/implanter.dm
code/modules/client/preference_setup/loadout/loadout_cyberware.dm
code/modules/nano/modules/crew_monitor.dm
code/modules/research/prosfab_designs.dm
html/create_object.html

Ports some prs:
[Geminus City #7](https://github.com/GeminusCity/Geminus-City/pull/7)
[Geminus City #12](https://github.com/GeminusCity/Geminus-City/pull/12)
[Geminus City #17](https://github.com/GeminusCity/Geminus-City/pull/17)
[Geminus City #19](https://github.com/GeminusCity/Geminus-City/pull/19)
They have some nice stuff + fixes.
:cl:
fix: fixed infinite cigs.
add: Added implanter and neural framework implant to prosthesis fabricator.
add: Added implanter zone selecting.
fix: fixed crew monitor program.
tweak: optimized create object admin menu.
/:cl:

Some ports

---

code/game/objects/items/devices/flash.dm

Maybe lets simple mobs get flashed

Flash affects simple mobs?

---

code/game/mecha/equipment/tools/tools.dm

changed mech diamond drill speed to 10 from 20
:cl:
Tweak: Changed the mech diamond drill attachment mining speed from 20 to 10 
/:cl:

Mech diamond drill change

---

code/game/jobs/job/hospital.dm
code/game/jobs/job/science.dm

changed: allows_synths = FALSE to TRUE for RND, Rotist and CMO

allow synths to work in rnd and hospital

---

code/modules/bounty/presets/agriculture.dm
code/modules/bounty/presets/drinks.dm
code/modules/bounty/presets/drugs.dm
code/modules/bounty/presets/food.dm
code/modules/bounty/presets/tech.dm
code/modules/bounty/presets/xenobio.dm
code/modules/research/designs.dm

Bounty Rework/Research Price Update

---

code/modules/bounty/presets/mining.dm

balance rework for mining. 15000 stacks for a small rewards was changed to something achievable in this lifetime. Overall less time spent grinding, but smaller bounties. There are still large bounties with high rewards though.
:cl:
/:cl:

More Bounty Rework

---

code/game/jobs/job/police.dm

:cl:
changed cop and wardens to allow synths COP is still whitelist required
/:cl:

synths can be pigs too

---

code/modules/mob/living/silicon/ai/ai.dm

Title.
No more runtime.
:cl:
fix: If an AI's power supply is created outside of one, it will delete itself and warn admins.
/:cl:

Fixes infinite runtimes on power supplies

---

code/modules/materials/material_recipes.dm
code/modules/reagents/distilling/Distilling-Recipes.dm

I did this for markus for the second time replaced antibodies with iron
replacing #121 for #120

pain synth blood 2

---

code/modules/mob/event_mobs.dm

Give Jesus Access!

---

code/modules/government/president/citizen_rights.dm

added
toggle_status = TRUE
to "nonnational" voting.

Update voting for non nationals

---

config/hardwhitelist.txt

dont mind me, just adding in my whitelist because staff are kinda slow

self whitelist

---

code/world.dm

hopefully
also even if no one is playing if anyone is interested it's good to have them spectate discord

makes discord links fixed
